# Generated by Django 4.2.3 on 2023-07-21 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('path_to_img', models.CharField(max_length=511)),
                ('cost', models.FloatField()),
                ('amount', models.CharField(max_length=127)),
                ('type', models.CharField(max_length=31)),
            ],
        ),
    ]
